import { GlobalResourceManager} from "smcomponents";
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ErrorBadUserNameOrPassword","The user name or password is incorrect")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","MembershipCreateStatusDuplicateEmail","A user name for that e-mail address already exists. Please enter a different e-mail address.")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","MembershipCreateStatusDuplicateUserName","User name already exists. Please enter a different user name.")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","MembershipCreateStatusProviderError","The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","MembershipCreateStatusUserRejected","The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorBadUserNameLength","The user name must be at least 4 and at most 255 characters long")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorBadFriendlyNameLength","The friendly name cannot be more than 255 characters long")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorBadPasswordLength","Password must be at least 7 and at most 50 characters long")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorBadPasswordStrength","A password needs to contain at least one special character e.g. @ or #")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorInvalidEmail","Invalid email. An email must use the format user@company.com")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorInvalidUserName","Invalid user name. It must contain only alphanumeric characters")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorPasswordConfirmationMismatch","Passwords do not match")
GlobalResourceManager.registerResourceEntry("HRApp.ErrorResources","ValidationErrorRequiredField","This field is required")