import { ResourceManager} from "smcomponents";
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
//Could not Transform the Attributes Section
export class ErrorResources {
   private static resourceMan : ResourceManager = null;
   private static resourceCulture : any = null;
   /*Could not transform the Attributes section*/
   public constructor () {
   }
   static get ResourceManager() : ResourceManager {
      if (ErrorResources.resourceMan === null) {
         var temp : ResourceManager = new ResourceManager ("HRApp.Web.Resources.ErrorResources");
         ErrorResources.resourceMan = temp;
      }
      return ErrorResources.resourceMan;
   }
   static set Culture(value : any) {
      ErrorResources.resourceCulture = value;
   }
   static get Culture() : any {
      return ErrorResources.resourceCulture;
   }
   static get ErrorBadUserNameOrPassword() : string {
      return ErrorResources.ResourceManager.GetString("ErrorBadUserNameOrPassword", ErrorResources.resourceCulture);
   }
   static get MembershipCreateStatusDuplicateEmail() : string {
      return ErrorResources.ResourceManager.GetString("MembershipCreateStatusDuplicateEmail", ErrorResources.resourceCulture);
   }
   static get MembershipCreateStatusDuplicateUserName() : string {
      return ErrorResources.ResourceManager.GetString("MembershipCreateStatusDuplicateUserName", ErrorResources.resourceCulture);
   }
   static get MembershipCreateStatusProviderError() : string {
      return ErrorResources.ResourceManager.GetString("MembershipCreateStatusProviderError", ErrorResources.resourceCulture);
   }
   static get MembershipCreateStatusUserRejected() : string {
      return ErrorResources.ResourceManager.GetString("MembershipCreateStatusUserRejected", ErrorResources.resourceCulture);
   }
   static get ValidationErrorBadFriendlyNameLength() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorBadFriendlyNameLength", ErrorResources.resourceCulture);
   }
   static get ValidationErrorBadPasswordLength() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorBadPasswordLength", ErrorResources.resourceCulture);
   }
   static get ValidationErrorBadPasswordStrength() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorBadPasswordStrength", ErrorResources.resourceCulture);
   }
   static get ValidationErrorBadUserNameLength() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorBadUserNameLength", ErrorResources.resourceCulture);
   }
   static get ValidationErrorInvalidEmail() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorInvalidEmail", ErrorResources.resourceCulture);
   }
   static get ValidationErrorInvalidUserName() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorInvalidUserName", ErrorResources.resourceCulture);
   }
   static get ValidationErrorPasswordConfirmationMismatch() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorPasswordConfirmationMismatch", ErrorResources.resourceCulture);
   }
   static get ValidationErrorRequiredField() : string {
      return ErrorResources.ResourceManager.GetString("ValidationErrorRequiredField", ErrorResources.resourceCulture);
   }
}