import { ResourceManager} from "smcomponents";
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
//Could not Transform the Attributes Section
export class RegistrationDataResources {
   private static resourceMan : ResourceManager = null;
   private static resourceCulture : any = null;
   /*Could not transform the Attributes section*/
   public constructor () {
   }
   static get ResourceManager() : ResourceManager {
      if (RegistrationDataResources.resourceMan === null) {
         var temp : ResourceManager = new ResourceManager ("HRApp.Web.Resources.RegistrationDataResources");
         RegistrationDataResources.resourceMan = temp;
      }
      return RegistrationDataResources.resourceMan;
   }
   static set Culture(value : any) {
      RegistrationDataResources.resourceCulture = value;
   }
   static get Culture() : any {
      return RegistrationDataResources.resourceCulture;
   }
   static get EmailLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("EmailLabel", RegistrationDataResources.resourceCulture);
   }
   static get FriendlyNameDescription() : string {
      return RegistrationDataResources.ResourceManager.GetString("FriendlyNameDescription", RegistrationDataResources.resourceCulture);
   }
   static get FriendlyNameLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("FriendlyNameLabel", RegistrationDataResources.resourceCulture);
   }
   static get PasswordConfirmationLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("PasswordConfirmationLabel", RegistrationDataResources.resourceCulture);
   }
   static get PasswordDescription() : string {
      return RegistrationDataResources.ResourceManager.GetString("PasswordDescription", RegistrationDataResources.resourceCulture);
   }
   static get PasswordLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("PasswordLabel", RegistrationDataResources.resourceCulture);
   }
   static get SecurityAnswerLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("SecurityAnswerLabel", RegistrationDataResources.resourceCulture);
   }
   static get SecurityQuestionLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("SecurityQuestionLabel", RegistrationDataResources.resourceCulture);
   }
   static get UserNameLabel() : string {
      return RegistrationDataResources.ResourceManager.GetString("UserNameLabel", RegistrationDataResources.resourceCulture);
   }
}