import { GlobalResourceManager} from "smcomponents";
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","AboutPageTitle","About")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ActivityLoadingUser","Initializing Application....")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ActivityLoggingIn","Logging in...")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ActivityRegisteringUser","Submitting Registration...")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","AlreadyRegisteredLabel","Already registered?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ApplicationName","HR Application")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","BackToLoginButton","Back to Login")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","CancelButton","Cancel")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ErrorBadUserNameOrPassword","The user name or password is incorrect")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ErrorLoginAfterRegistrationFailed","Registration was successful but there was a problem while trying to log in with your credentials: {0}")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ErrorWindowErrorDetails","Error Details")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ErrorWindowGenericError","An unknown error has occurred. Please contact your administrator for help")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","ErrorWindowTitle","Error")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","HomePageTitle","Home")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","LoginButton","login")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","LoginWindowTitle","Login")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","LogOffButton","logout")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","NotRegisteredYetLabel","Not registered yet?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","OKButton","OK")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","RegisterNowButton","Register now")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","RegistrationFormHeader","Please complete all required fields to create your account")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","RegistrationWindowTitle","Register")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","RememberMeLabel","Keep me signed in")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.ApplicationStrings","WelcomeMessage","Welcome {0}")