import { GlobalResourceManager} from "smcomponents";
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","BestChildhoodFriendQuestion","What is the name of your favorite childhood friend?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","ChildhoodNicknameQuestion","What was your childhood nickname?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","FirstCarColorQuestion","What was the color of your first car?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","FirstCarMakeAndModelQuestion","What was the make and model of your first car?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","FirstJobCityQuestion","In what city or town was your first job?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","LastVacationLocationQuestion","Where did you vacation last year?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","MaternalGrandmothersMaidenNameQuestion","What is your maternal grandmother's maiden name?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","MothersMaidenNameQuestion","What is your mother's maiden name?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","PetNameQuestion","What is your pet's name?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","SixthGradeSchoolNameQuestion","What school did you attend for sixth grade?")
GlobalResourceManager.registerResourceEntry("HRApp.Assets.Resources.SecurityQuestions","YearFatherWasBornQuestion","In what year was your father born?")