import { ResourceManager} from "smcomponents";
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
//Could not Transform the Attributes Section
export class SecurityQuestions {
   private static resourceMan : ResourceManager = null;
   private static resourceCulture : any = null;
   /*Could not transform the Attributes section*/
   public constructor () {
   }
   static get ResourceManager() : ResourceManager {
      if (SecurityQuestions.resourceMan === null) {
         var temp : ResourceManager = new ResourceManager ("HRApp.Assets.Resources.SecurityQuestions");
         SecurityQuestions.resourceMan = temp;
      }
      return SecurityQuestions.resourceMan;
   }
   static set Culture(value : any) {
      SecurityQuestions.resourceCulture = value;
   }
   static get Culture() : any {
      return SecurityQuestions.resourceCulture;
   }
   static get BestChildhoodFriendQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("BestChildhoodFriendQuestion", SecurityQuestions.resourceCulture);
   }
   static get ChildhoodNicknameQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("ChildhoodNicknameQuestion", SecurityQuestions.resourceCulture);
   }
   static get FirstCarColorQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("FirstCarColorQuestion", SecurityQuestions.resourceCulture);
   }
   static get FirstCarMakeAndModelQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("FirstCarMakeAndModelQuestion", SecurityQuestions.resourceCulture);
   }
   static get FirstJobCityQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("FirstJobCityQuestion", SecurityQuestions.resourceCulture);
   }
   static get LastVacationLocationQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("LastVacationLocationQuestion", SecurityQuestions.resourceCulture);
   }
   static get MaternalGrandmothersMaidenNameQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("MaternalGrandmothersMaidenNameQuestion", SecurityQuestions.resourceCulture);
   }
   static get MothersMaidenNameQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("MothersMaidenNameQuestion", SecurityQuestions.resourceCulture);
   }
   static get PetNameQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("PetNameQuestion", SecurityQuestions.resourceCulture);
   }
   static get SixthGradeSchoolNameQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("SixthGradeSchoolNameQuestion", SecurityQuestions.resourceCulture);
   }
   static get YearFatherWasBornQuestion() : string {
      return SecurityQuestions.ResourceManager.GetString("YearFatherWasBornQuestion", SecurityQuestions.resourceCulture);
   }
}